[build]
buildCommand = "npm run build"
installCommand = "npm install"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
watchPatterns = ["**/*"]
