[build]
buildCommand = "npm run build"
installCommand = "npm install"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
watchPatterns = ["/*/**", "/*.tsx", "/*.ts", "/*.js", "/*.json"]
